{ config, lib, pkgs, nasInternal, ... }:

let
  storePath = "/var/lib/nas-control/services.json";
  effectivePath = "/run/nas-control/effective-endpoints.json";
  portalPath = "/run/nas-control/portal.json";
  fragmentPath = "/run/nas-control/caddy-managed.conf";
  copypartyV2Path = "/var/lib/copyparty/user.d/50-v2-storage.conf";
  secretReady = "${nasInternal.secretRoot}/ready";
  reconcilePost = pkgs.writeShellScript "nas-managed-services-reconcile-post" ''
    set -eu
    ${nasInternal.nasPythonApplication}/bin/nas-copyparty-projection \
      --effective ${effectivePath} \
      --output ${copypartyV2Path}
    ${pkgs.systemd}/bin/systemctl try-reload-or-restart copyparty.service
  '';
in
{
  config = {
    systemd.tmpfiles.rules = [
      "d /var/lib/nas-control 0750 nas-feature-gate nas-feature-control -"
      "d /run/nas-control 0755 root root -"
      "d /var/lib/copyparty/user.d 0750 copyparty copyparty -"
      "f ${storePath} 0600 nas-feature-gate nas-feature-control - {\"schemaVersion\":2,\"storageResources\":{},\"networkProfiles\":{},\"services\":{}}"
      "f ${fragmentPath} 0644 root root - \"# Managed-services Caddy sites — generated by nas-managed-service\\n\""
    ];

    systemd.services.nas-managed-services-reconcile = {
      description = "Rebuild V2 projections and enforce application availability/lifecycle";
      wantedBy = [ "nas-protected-services.target" ];
      partOf = [ "nas-protected-services.target" ];
      requires = [ "nas-zfs-mount-guard.service" "nas-identity-sync.service" "caddy.service" ];
      after = [
        "network-online.target"
        "nas-zfs-mount-guard.service"
        "nas-identity-sync.service"
        "caddy.service"
      ];
      unitConfig.ConditionPathExists = secretReady;
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${nasInternal.nasPythonApplication}/bin/nas-managed-service reconcile";
        ExecStartPost = reconcilePost;
        RemainAfterExit = false;
      };
    };

    systemd.paths.nas-managed-services-reconcile = {
      description = "Watch for managed service store changes while the protected control plane is unlocked";
      wantedBy = [ "nas-protected-services.target" ];
      partOf = [ "nas-protected-services.target" ];
      unitConfig.ConditionPathExists = secretReady;
      pathConfig.PathChanged = storePath;
    };

    systemd.services.nas-managed-services-reap = {
      description = "Stop idle Managed Services V2 on-demand applications";
      partOf = [ "nas-protected-services.target" ];
      unitConfig.ConditionPathExists = secretReady;
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${nasInternal.nasPythonApplication}/bin/nas-managed-service reap";
        NoNewPrivileges = true;
        PrivateTmp = true;
      };
    };

    systemd.timers.nas-managed-services-reap = {
      description = "Periodically reap idle Managed Services V2 on-demand applications";
      wantedBy = [ "nas-protected-services.target" ];
      partOf = [ "nas-protected-services.target" ];
      unitConfig.ConditionPathExists = secretReady;
      timerConfig = {
        OnActiveSec = "2m";
        OnUnitActiveSec = "1m";
        AccuracySec = "15s";
        Persistent = false;
      };
    };

    environment.etc."nas-control/effective-endpoints.json".source = effectivePath;

    services.caddy.extraConfig = lib.mkAfter ''
      import ${fragmentPath}
    '';
    services.caddy.virtualHosts.${config.networking.hostName + ".local"}.extraConfig = lib.mkAfter ''
      import nas_managed_paths
    '';
    systemd.services.caddy.restartTriggers = [ fragmentPath ];
  };
}
