{ config, lib, pkgs, nasInternal, ... }:

let
  cfg = config.nas;
  storePath = "/var/lib/nas-control/services.json";
  effectivePath = "/run/nas-control/effective-endpoints.json";
  portalPath = "/run/nas-control/portal.json";
  fragmentPath = "/run/nas-control/caddy-managed.conf";
in
{
  config = lib.mkIf true {
    systemd.tmpfiles.rules = [
      "d /var/lib/nas-control 0750 nas-feature-gate nas-feature-control -"
      "d /run/nas-control 0755 root root -"
      "f ${storePath} 0600 nas-feature-gate nas-feature-control - {\"schemaVersion\":2,\"services\":{}}"
      "f ${fragmentPath} 0644 root root - \"# Managed-services Caddy sites — generated by nas-managed-service\\n\""
    ];

    systemd.services.nas-managed-services-reconcile = {
      description = "Rebuild effective service registry and portal projection";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${nasInternal.nasPythonApplication}/bin/nas-managed-service reconcile";
        RemainAfterExit = false;
      };
    };

    systemd.paths.nas-managed-services-reconcile = {
      description = "Watch for managed service store changes";
      wantedBy = [ "multi-user.target" ];
      pathConfig = {
        PathChanged = storePath;
      };
    };

    environment.etc."nas-control/effective-endpoints.json".source = effectivePath;

    # The generated file defines complete hostname/port site blocks plus the
    # nas_managed_paths snippet. Import complete sites globally, then import the
    # path-only snippet inside the appliance's existing nas.local site so we do
    # not create an ambiguous duplicate nas.local site definition.
    services.caddy.extraConfig = lib.mkAfter ''
      import ${fragmentPath}
    '';
    services.caddy.virtualHosts.${config.networking.hostName + ".local"}.extraConfig = lib.mkAfter ''
      import nas_managed_paths
    '';
    systemd.services.caddy.restartTriggers = [ fragmentPath ];
  };
}
