{ config, lib, pkgs, nasInternal, ... }:

let
  inherit (nasInternal)
    authentikPort
    caddyForwardAuth
    caddyOnDemandTransport
    cfg
    lanHost
    nasPortalStatic
  ;
  authentikPathNoSlash = lib.removeSuffix "/" cfg.identity.authentikPath;
in
{
  config.services.caddy = {
    enable = true;
    openFirewall = false;
    logFormat = ''format json'';
    virtualHosts.${lanHost}.extraConfig = ''
      tls internal
      encode zstd gzip
      header {
        -Server
        X-Content-Type-Options "nosniff"
        Referrer-Policy "no-referrer"
        Permissions-Policy "camera=(), microphone=(), geolocation=()"
      }

      # Recreate identity headers only from Authentik forward-auth.
      request_header -Remote-User
      request_header -Remote-Groups
      request_header -Remote-Name
      request_header -Remote-Email
      request_header -Remote-Role
      request_header -X-Authentik-Username
      request_header -X-Authentik-Groups
      request_header -X-Authentik-Name
      request_header -X-Authentik-Email

      log {
        output file ${config.services.caddy.logDir}/access.log {
          mode 0640
          roll_size 100MiB
          roll_keep 10
          roll_keep_for 720h
        }
        format json
      }

      # Authentik bootstrap/global routes remain static until Caddy itself moves
      # behind a non-cyclic V2 bootstrap boundary.
      @authentikOutpost path /outpost.goauthentik.io/*
      handle @authentikOutpost {
        uri replace /outpost.goauthentik.io ${cfg.identity.authentikPath}outpost.goauthentik.io
        reverse_proxy 127.0.0.1:${toString authentikPort} {
          header_up Host {http.request.host}
          header_up X-Forwarded-Proto https
          header_up X-Forwarded-For {remote_host}
        }
      }
      redir ${authentikPathNoSlash} ${cfg.identity.authentikPath}
      @authentikUi path ${cfg.identity.authentikPath}*
      handle @authentikUi {
        reverse_proxy 127.0.0.1:${toString authentikPort} {
          header_up Host {http.request.host}
          header_up X-Forwarded-Proto https
          header_up X-Forwarded-For {remote_host}
        }
      }

      # These are only URL-canonicalization redirects. The corresponding reverse
      # proxies, authorization, readiness, and on-demand lifecycle are V2-owned.
      ${lib.optionalString cfg.ai.enable ''
      redir /ai/runtime /ai/runtime/
      ${lib.optionalString cfg.ai.modelDownloader.enable ''
      redir /ai/models /ai/models/
      ''}
      ''}
      ${lib.optionalString (cfg.observability.enable && cfg.alerting.enable) ''
      redir /alerts /alerts/
      ''}
      ${lib.optionalString cfg.observability.enable ''
      redir /victoriametrics /victoriametrics/vmui
      ${lib.optionalString cfg.observability.grafana.enable ''
      redir /metrics /metrics/
      ''}
      ''}
      ${lib.optionalString cfg.observability.ntfy.enable ''
      redir /notifications /notifications/
      ''}
      ${lib.optionalString (cfg.power.ups.enable && cfg.power.ups.web.enable) ''
      redir /ups /ups/
      ''}

      # Open WebUI keeps its special role-header translation here temporarily,
      # but authorization is now a canonical Authentik capability check and wake
      # is handled only by the authorization-free V2 socket helper.
      ${lib.optionalString cfg.ai.enable ''
      redir /ai /ai/
      @aiWorkspace path /ai/*
      handle @aiWorkspace {
        route {
          ${caddyForwardAuth}
          @missingAiWorkspaceAccess {
            not header_regexp Remote-Groups (?i)(^|[|,][[:space:]]*)application\.ai-workspace\.access([[:space:]]*[|,]|$)
          }
          respond @missingAiWorkspaceAccess 403
          forward_auth unix//run/nas-control/wake.sock {
            uri /wake?service=ai-workspace
          }
          request_header Remote-Role user
          @aiWorkspaceAdministrator header_regexp Remote-Groups (?i)(^|[|,][[:space:]]*)application\.ai-workspace\.admin([[:space:]]*[|,]|$)
          request_header @aiWorkspaceAdministrator Remote-Role admin
          uri strip_prefix /ai
          reverse_proxy 127.0.0.1:${toString cfg.ai.openWebuiPort} {
            header_up Remote-User {http.request.header.Remote-User}
            header_up Remote-Groups {http.request.header.Remote-Groups}
            header_up Remote-Name {http.request.header.Remote-Name}
            header_up Remote-Email {http.request.header.Remote-Email}
            header_up Remote-Role {http.request.header.Remote-Role}
            header_up X-Forwarded-Prefix /ai
            header_up X-Forwarded-Proto https
            ${caddyOnDemandTransport}
          }
        }
      }
      ''}

      # The downloader's primary /ai/models route is generated by V2. These
      # compatibility paths exist only because the current upstream emits a few
      # absolute URLs; they use the same canonical capability and V2 lease.
      ${lib.optionalString (cfg.ai.enable && cfg.ai.modelDownloader.enable) ''
      @hfdAbsoluteAssets {
        path /css/style.css /js/app.js
        header_regexp hfdAssetRef Referer ^https://${lanHost}/ai/models(/.*)?$
      }
      handle @hfdAbsoluteAssets {
        route {
          ${caddyForwardAuth}
          @missingAiDownloaderAssetAccess {
            not header_regexp Remote-Groups (?i)(^|[|,][[:space:]]*)application\.ai-downloader\.admin([[:space:]]*[|,]|$)
          }
          respond @missingAiDownloaderAssetAccess 403
          forward_auth unix//run/nas-control/wake.sock {
            uri /wake?service=ai-downloader
          }
          reverse_proxy 127.0.0.1:${toString cfg.ai.modelDownloader.port} {
            ${caddyOnDemandTransport}
          }
        }
      }
      @hfdAbsoluteWebSocket {
        path /api/ws
        header Origin https://${lanHost}
        header Connection *Upgrade*
        header Upgrade websocket
      }
      handle @hfdAbsoluteWebSocket {
        route {
          ${caddyForwardAuth}
          @missingAiDownloaderWsAccess {
            not header_regexp Remote-Groups (?i)(^|[|,][[:space:]]*)application\.ai-downloader\.admin([[:space:]]*[|,]|$)
          }
          respond @missingAiDownloaderWsAccess 403
          forward_auth unix//run/nas-control/wake.sock {
            uri /wake?service=ai-downloader
          }
          reverse_proxy 127.0.0.1:${toString cfg.ai.modelDownloader.port} {
            ${caddyOnDemandTransport}
          }
        }
      }
      @hfdAbsoluteApi {
        path /api/*
        header_regexp hfdApiRef Referer ^https://${lanHost}/ai/models(/.*)?$
      }
      handle @hfdAbsoluteApi {
        route {
          ${caddyForwardAuth}
          @missingAiDownloaderApiAccess {
            not header_regexp Remote-Groups (?i)(^|[|,][[:space:]]*)application\.ai-downloader\.admin([[:space:]]*[|,]|$)
          }
          respond @missingAiDownloaderApiAccess 403
          forward_auth unix//run/nas-control/wake.sock {
            uri /wake?service=ai-downloader
          }
          reverse_proxy 127.0.0.1:${toString cfg.ai.modelDownloader.port} {
            ${caddyOnDemandTransport}
          }
        }
      }
      ''}

      handle /settings/syncthing {
        route {
          ${caddyForwardAuth}
          @missingSyncthingSettingsAccess {
            not header_regexp Remote-Groups (?i)(^|[|,][[:space:]]*)application\.syncthing\.admin([[:space:]]*[|,]|$)
          }
          respond @missingSyncthingSettingsAccess 403
          redir ${cfg.identity.authentikPath}if/flow/nas-user-settings/
        }
      }
      redir /settings ${cfg.identity.authentikPath}if/user/
      redir /settings/ ${cfg.identity.authentikPath}if/user/

      # V2 application routes are imported before this bootstrap/fallback block.
      handle {
        route {
          ${caddyForwardAuth}
          root * ${nasPortalStatic}/share/nas-portal
          rewrite * /index.html
          templates
          file_server
        }
      }
    '';
  };
}
