#!/usr/bin/env python3
"""Generate Copyparty volume policy from Managed Services V2 resources.

V2 owns storage resources, Authentik owns group membership/authorization, and
Copyparty consumes the projection. This module never creates users or mutates
Authentik. It emits group-based ACLs that match deterministic Authentik
capability-group names.

User-scoped resources are deliberately not projected as their parent path. They
require an identity-bound realization of ``pathTemplate``; until that projection
is explicitly qualified against the pinned Copyparty version, omission is safer
than exposing every user's state beneath one shared volume.
"""

from __future__ import annotations

import json
import os
import pathlib
import tempfile
from typing import Any

from nas_managed_resources import capability_group_name, storage_capability

DEFAULT_EFFECTIVE_PATH = pathlib.Path(
    os.environ.get("NAS_EFFECTIVE_REGISTRY", "/run/nas-control/effective-endpoints.json")
)
DEFAULT_CONFIG_PATH = pathlib.Path(
    os.environ.get("NAS_COPYPARTY_V2_CONFIG", "/var/lib/copyparty/user.d/50-v2-storage.conf")
)
ADMIN_GROUP = "nas_admin"

COPYPARTY_PERMISSIONS = {
    "read": "r",
    "write": "w",
    "move": "m",
    "delete": "d",
    "admin": "A",
}


class CopypartyProjectionError(RuntimeError):
    pass


def capability_group(resource_id: str, capability: str) -> str:
    """Return the deterministic Authentik group backing a storage capability."""

    return capability_group_name(storage_capability(resource_id, capability))


def _volume_url(resource_id: str) -> str:
    return f"/{resource_id}"


def _render_access(resource_id: str, capabilities: list[str]) -> list[str]:
    lines = [f"    A: @{ADMIN_GROUP}"]
    for capability in capabilities:
        permission = COPYPARTY_PERMISSIONS.get(capability)
        if permission is None:
            raise CopypartyProjectionError(
                f"Storage resource {resource_id!r} has unsupported Copyparty capability {capability!r}"
            )
        lines.append(f"    {permission}: @{capability_group(resource_id, capability)}")
    return lines


def render_config(effective: dict[str, Any]) -> str:
    resources = effective.get("storageResources", {})
    if not isinstance(resources, dict):
        raise CopypartyProjectionError("effective storageResources must be an object")

    lines = [
        "# Generated by nas-managed-service; do not edit.",
        "# Authorization assignments live in Authentik.",
        "",
        "[/]",
        "/",
        "  accs:",
        f"    A: @{ADMIN_GROUP}",
    ]

    for resource_id in sorted(resources):
        resource = resources[resource_id]
        if not isinstance(resource, dict):
            raise CopypartyProjectionError(f"Storage resource {resource_id!r} must be an object")
        path = resource.get("path")
        capabilities = resource.get("capabilities")
        scope = resource.get("scope", "system")
        if not isinstance(path, str) or not path.startswith("/"):
            raise CopypartyProjectionError(f"Storage resource {resource_id!r} has invalid path")
        if not isinstance(capabilities, list) or not capabilities:
            raise CopypartyProjectionError(f"Storage resource {resource_id!r} has no capabilities")
        if scope == "user":
            path_template = resource.get("pathTemplate")
            if not isinstance(path_template, str) or "{user}" not in path_template:
                raise CopypartyProjectionError(
                    f"User-scoped storage resource {resource_id!r} lacks a valid pathTemplate"
                )
            lines.extend(
                [
                    "",
                    f"# user-scoped resource {resource_id!r} intentionally omitted from generic projection",
                    "# it must be realized for one authenticated identity before mounting",
                ]
            )
            continue
        if scope not in {"system", "instance"}:
            raise CopypartyProjectionError(f"Storage resource {resource_id!r} has invalid scope {scope!r}")
        lines.extend(
            [
                "",
                f"[{_volume_url(resource_id)}]",
                path,
                "  accs:",
                *_render_access(resource_id, capabilities),
            ]
        )
    return "\n".join(lines) + "\n"


def atomic_write_config(text: str, path: pathlib.Path = DEFAULT_CONFIG_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    tmp_path = pathlib.Path(tmp)
    try:
        with open(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        tmp_path.chmod(0o644)
        tmp_path.replace(path)
        dir_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    finally:
        tmp_path.unlink(missing_ok=True)


def reconcile_from_effective(
    effective_path: pathlib.Path = DEFAULT_EFFECTIVE_PATH,
    config_path: pathlib.Path = DEFAULT_CONFIG_PATH,
) -> str:
    try:
        effective = json.loads(effective_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise CopypartyProjectionError(f"Effective registry is missing: {effective_path}") from exc
    except (OSError, json.JSONDecodeError) as exc:
        raise CopypartyProjectionError(f"Unable to read effective registry: {exc}") from exc
    text = render_config(effective)
    atomic_write_config(text, config_path)
    return text


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(prog="nas-copyparty-projection")
    parser.add_argument("--effective", type=pathlib.Path, default=DEFAULT_EFFECTIVE_PATH)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_CONFIG_PATH)
    parser.add_argument("--print", action="store_true", dest="print_output")
    args = parser.parse_args(argv)
    try:
        text = reconcile_from_effective(args.effective, args.output)
    except CopypartyProjectionError as exc:
        parser.error(str(exc))
    if args.print_output:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
