#!/usr/bin/env python3
"""Device-resource compatibility layer for Managed Services V2.

This layer is intentionally orthogonal to lifecycle and dependency handling. It
resolves ``resources.gpus`` into ``resolvedDevices`` and delegates execution to
the existing generic runtime adapters. No service IDs or application names are
special-cased.
"""

from __future__ import annotations

import copy
import os
import pathlib
import subprocess
import tempfile
from typing import Any

import nas_managed_service_v2 as _v2
from nas_managed_devices import flattened_device_paths, resolve_service_devices
from nas_managed_resources import ManagedResourceError

_BASE_APPLY_RUNTIME = _v2._apply_runtime
SYSTEMD_DROPIN_ROOT = pathlib.Path("/run/systemd/system")
SYSTEMD_DROPIN_NAME = "90-nixos-nas-v2-devices.conf"
GENERATED_MARKER = "# Generated by NixOS NAS Managed Services V2; do not edit."


def _systemd_dropin(unit: str) -> pathlib.Path:
    return SYSTEMD_DROPIN_ROOT / f"{unit}.d" / SYSTEMD_DROPIN_NAME


def _atomic_write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = pathlib.Path(name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _render_systemd_device_policy(resolved: list[dict[str, Any]]) -> str:
    paths = flattened_device_paths(resolved)
    if not paths:
        return GENERATED_MARKER + "\n"
    lines = [
        GENERATED_MARKER,
        "",
        "[Service]",
        # Keep the host's device namespace available, while DeviceAllow and
        # ordinary Unix permissions define the explicitly granted GPU nodes.
        "PrivateDevices=no",
        "SupplementaryGroups=render video",
    ]
    for path in paths:
        lines.append(f"DeviceAllow={path} rwm")
    return "\n".join(lines) + "\n"


def _remove_generated_dropin(unit: str) -> bool:
    path = _systemd_dropin(unit)
    try:
        content = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return False
    if not content.startswith(GENERATED_MARKER):
        raise ManagedResourceError(f"Refusing to remove non-generated systemd device policy {path}")
    path.unlink()
    try:
        path.parent.rmdir()
    except OSError:
        pass
    return True


def _prepare_systemd_devices(service_id: str, service: dict[str, Any]) -> list[str]:
    units = _v2._systemd_units(service_id, service)
    resolved = service.get("resolvedDevices") or []
    paths = flattened_device_paths(resolved)
    changed = False
    for unit in units:
        path = _systemd_dropin(unit)
        if paths:
            if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                raise ManagedResourceError(f"Refusing to overwrite non-generated systemd device policy {path}")
            _atomic_write(path, _render_systemd_device_policy(resolved))
            changed = True
        else:
            changed = _remove_generated_dropin(unit) or changed
    if changed:
        subprocess.run(["systemctl", "daemon-reload"], check=True)
    return paths


def _cleanup_systemd_devices(service_id: str, service: dict[str, Any]) -> None:
    changed = False
    for unit in _v2._systemd_units(service_id, service):
        changed = _remove_generated_dropin(unit) or changed
    if changed:
        subprocess.run(["systemctl", "daemon-reload"], check=True)


def _apply_runtime(service_id: str, service: dict[str, Any], *, enabled: bool) -> dict[str, Any]:
    candidate = copy.deepcopy(service)
    try:
        candidate["resolvedDevices"] = resolve_service_devices(candidate)
    except ManagedResourceError:
        raise
    except OSError as exc:
        raise ManagedResourceError(f"Service {service_id}: unable to resolve GPU resources: {exc}") from exc

    runtime_type = (candidate.get("runtime") or {}).get("type")
    if runtime_type == "systemd":
        if enabled:
            _prepare_systemd_devices(service_id, candidate)
            result = _BASE_APPLY_RUNTIME(service_id, candidate, enabled=True)
        else:
            result = _BASE_APPLY_RUNTIME(service_id, candidate, enabled=False)
            _cleanup_systemd_devices(service_id, candidate)
    else:
        result = _BASE_APPLY_RUNTIME(service_id, candidate, enabled=enabled)

    if isinstance(result, dict):
        result["resolvedDevices"] = candidate["resolvedDevices"]
    return result


def _install() -> None:
    _v2._apply_runtime = _apply_runtime


def main(argv: list[str] | None = None) -> int:
    _install()
    return _v2.main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
