#!/usr/bin/env python3
"""Thin Podman Quadlet adapter for managed services.

Nix-nas owns NAS-specific policy and metadata. Podman owns Quadlet parsing,
application installation, drop-in merging, systemd reloads, and removal.
V2 storage/network policy is projected as generated native Quadlet fragments
rather than re-rendering the user-authored container definition.
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import subprocess
import tempfile
from typing import Any

from nas_managed_network import render_network_quadlet, service_network
from nas_managed_service import ManagedServiceError

APP_ROOT = pathlib.Path("/var/lib/nas-control/apps")
UNIT_RE = re.compile(r"^[A-Za-z0-9_.@:-]+\.service$")
GENERATED_DROPIN = "90-nixos-nas-v2-storage.conf"
GENERATED_MARKER = "# Generated by NixOS NAS Managed Services V2; do not edit."


def _quadlet_source(service_id: str, service: dict[str, Any]) -> pathlib.Path:
    runtime = service.get("runtime", {})
    if runtime.get("type") != "quadlet":
        raise ManagedServiceError(f"Service {service_id} is not a Quadlet service")

    source = runtime.get("source", "")
    if not isinstance(source, str) or not pathlib.PurePosixPath(source).is_absolute():
        raise ManagedServiceError(f"Podman source for {service_id} must be under {APP_ROOT / service_id}/")
    app_root = APP_ROOT.resolve()
    root = (app_root / service_id).resolve()
    path = pathlib.Path(source).resolve()
    try:
        root.relative_to(app_root)
        path.relative_to(root)
    except ValueError as exc:
        raise ManagedServiceError(f"Podman source for {service_id} must be under {root}/") from exc

    if path.suffix != ".container":
        raise ManagedServiceError(f"Podman source for {service_id} must be a native .container Quadlet file")
    return path


def _application_root(service_id: str, source: pathlib.Path) -> pathlib.Path:
    app_root = APP_ROOT.resolve()
    root = (app_root / service_id).resolve()
    try:
        source.resolve().relative_to(root)
    except ValueError as exc:
        raise ManagedServiceError(f"Podman source for {service_id} must be under {root}/") from exc
    return root


def _v2_mounts(service: dict[str, Any]) -> list[dict[str, Any]]:
    mounts = service.get("resolvedStorage") or []
    if not isinstance(mounts, list):
        raise ManagedServiceError("resolvedStorage must be an array")
    selected = []
    for mount in mounts:
        if not isinstance(mount, dict) or "resource" not in mount:
            continue
        host = mount.get("hostPath")
        guest = mount.get("guestPath")
        mode = mount.get("mode")
        if not isinstance(host, str) or not host.startswith("/"):
            raise ManagedServiceError("resolved V2 storage hostPath must be absolute")
        if not isinstance(guest, str) or not guest.startswith("/"):
            raise ManagedServiceError("resolved V2 storage guestPath must be absolute")
        if any(char in host or char in guest for char in ("\x00", "\r", "\n", ":")):
            raise ManagedServiceError("resolved V2 storage path contains an unsafe Quadlet delimiter")
        if mode not in {"ro", "rw"}:
            raise ManagedServiceError("resolved V2 storage mode must be ro or rw")
        selected.append(mount)
    return selected


def _v2_network(service_id: str, service: dict[str, Any]) -> dict[str, Any] | None:
    resolved = service.get("resolvedNetwork")
    if resolved is None:
        return None
    if not isinstance(resolved, dict):
        raise ManagedServiceError("resolvedNetwork must be an object")
    identity = resolved.get("identity")
    expected = service_network(service_id)
    if identity != expected:
        raise ManagedServiceError(f"Service {service_id}: resolved network identity is invalid")
    return resolved


def render_policy_dropin(service_id: str, service: dict[str, Any]) -> str:
    lines = [GENERATED_MARKER]
    mounts = _v2_mounts(service)
    network = _v2_network(service_id, service)
    if mounts or network is not None:
        lines.extend(["", "[Container]"])
        for mount in mounts:
            lines.append(f"Volume={mount['hostPath']}:{mount['guestPath']}:{mount['mode']}")
        if network is not None:
            lines.append(f"Network={network['identity']['quadlet']}")
    return "\n".join(lines) + "\n"


def render_storage_dropin(service: dict[str, Any]) -> str:
    """Compatibility helper retained for tests/callers that only exercise storage."""
    lines = [GENERATED_MARKER]
    mounts = _v2_mounts(service)
    if mounts:
        lines.extend(["", "[Container]"])
        for mount in mounts:
            lines.append(f"Volume={mount['hostPath']}:{mount['guestPath']}:{mount['mode']}")
    return "\n".join(lines) + "\n"


def _dropin_path(source: pathlib.Path) -> pathlib.Path:
    return source.parent / f"{source.name}.d" / GENERATED_DROPIN


def _atomic_write(path: pathlib.Path, text: str, *, mode: int = 0o640) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    tmp_path = pathlib.Path(temporary)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(tmp_path, mode)
        os.replace(tmp_path, path)
        dir_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)
    finally:
        tmp_path.unlink(missing_ok=True)


def _write_generated_policy(source: pathlib.Path, service_id: str, service: dict[str, Any]) -> tuple[pathlib.Path | None, pathlib.Path | None]:
    dropin = _dropin_path(source)
    mounts = _v2_mounts(service)
    network = _v2_network(service_id, service)
    if not mounts and network is None:
        try:
            existing = dropin.read_text(encoding="utf-8")
        except FileNotFoundError:
            existing = None
        if existing is not None:
            if not existing.startswith(GENERATED_MARKER):
                raise ManagedServiceError(f"Refusing to remove non-generated Quadlet drop-in {dropin}")
            dropin.unlink()
            try:
                dropin.parent.rmdir()
            except OSError:
                pass
    else:
        if dropin.exists() and not dropin.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            raise ManagedServiceError(f"Refusing to overwrite non-generated Quadlet drop-in {dropin}")
        _atomic_write(dropin, render_policy_dropin(service_id, service))

    network_path: pathlib.Path | None = None
    if network is not None:
        root = _application_root(service_id, source)
        network_path = root / network["identity"]["quadlet"]
        if network_path.exists() and not network_path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            raise ManagedServiceError(f"Refusing to overwrite non-generated Quadlet network {network_path}")
        _atomic_write(network_path, render_network_quadlet(service_id))
    return (dropin if (mounts or network is not None) else None, network_path)


def plan_podman(service_id: str, service: dict[str, Any]) -> dict[str, Any]:
    runtime = service.get("runtime", {})
    if runtime.get("type") != "quadlet":
        return {"actions": [], "warnings": [f"Service {service_id} is not a Quadlet service"]}

    source = _quadlet_source(service_id, service)
    application_root = _application_root(service_id, source)
    unit = f"{source.stem}.service"
    v2_mounts = _v2_mounts(service)
    v2_network = _v2_network(service_id, service)
    return {
        "service": service_id,
        "runtime": "podman-quadlet",
        "source": str(source),
        "applicationSource": str(application_root),
        "application": service_id,
        "unit": unit,
        "enabled": bool(service.get("enabled")),
        "resolvedStorage": v2_mounts,
        "resolvedNetwork": v2_network,
        "actions": [
            {"type": "podman-quadlet-install", "source": str(application_root), "application": service_id, "replace": True},
            {"type": "systemd-unit", "unit": unit, "operation": "restart" if service.get("enabled") else "stop"},
        ],
    }


def apply_podman(service_id: str, service: dict[str, Any], *, dry_run: bool = False) -> dict[str, Any]:
    plan = plan_podman(service_id, service)
    if dry_run or not plan["actions"]:
        return plan

    source = pathlib.Path(plan["source"])
    _write_generated_policy(source, service_id, service)
    subprocess.run(
        ["podman", "quadlet", "install", "--replace", f"--application={plan['application']}", plan["applicationSource"]],
        check=True,
    )
    listed = subprocess.run(
        ["podman", "quadlet", "list", "--filter", f"name={source.name}", "--format", "json"],
        check=True,
        capture_output=True,
        text=True,
    )
    try:
        rows = json.loads(listed.stdout)
    except (json.JSONDecodeError, TypeError) as exc:
        raise ManagedServiceError(f"Podman returned invalid Quadlet metadata for {service_id}") from exc
    source_name = source.name
    units: list[str] = []
    if isinstance(rows, list):
        for row in rows:
            if not isinstance(row, dict) or row.get("Name") != source_name or row.get("App") != service_id:
                continue
            unit = row.get("UnitName")
            if isinstance(unit, str):
                units.append(unit)
    if len(units) != 1 or not UNIT_RE.fullmatch(units[0]):
        raise ManagedServiceError(f"Podman did not report one valid unit for {service_id}")
    plan["unit"] = units[0]
    operation = "restart" if plan["enabled"] else "stop"
    subprocess.run(["systemctl", operation, plan["unit"]], check=True)
    return plan


def _remove_generated_sources(service_id: str) -> None:
    root = (APP_ROOT / service_id)
    if not root.exists():
        return
    network_path = root / service_network(service_id)["quadlet"]
    if network_path.exists():
        try:
            if network_path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                network_path.unlink()
        except OSError:
            pass
    for dropin in root.rglob(GENERATED_DROPIN):
        try:
            if dropin.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                dropin.unlink()
                try:
                    dropin.parent.rmdir()
                except OSError:
                    pass
        except OSError:
            continue


def remove_podman(service_id: str, *, dry_run: bool = False) -> None:
    if dry_run:
        return
    subprocess.run(
        ["podman", "quadlet", "rm", "--force", "--ignore", "--recursive", service_id],
        check=True,
    )
    _remove_generated_sources(service_id)
