#!/usr/bin/env python3
"""Generate native systemd timers for V2 job schedules."""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import tempfile
from typing import Any

UNIT_ROOT = pathlib.Path("/run/systemd/system")
MARKER = "# Generated by NixOS NAS Managed Services V2; do not edit."
SERVICE_ID_RE = re.compile(r"^[a-z][a-z0-9-]{0,47}$")


class V2ScheduleError(RuntimeError):
    pass


def _atomic_write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = pathlib.Path(name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def timer_name(service_id: str, index: int) -> str:
    if not SERVICE_ID_RE.fullmatch(service_id):
        raise V2ScheduleError(f"Invalid V2 service id {service_id!r}")
    return f"nas-v2-job-{service_id}-{index}.timer"


def runner_name(service_id: str, index: int) -> str:
    if not SERVICE_ID_RE.fullmatch(service_id):
        raise V2ScheduleError(f"Invalid V2 service id {service_id!r}")
    return f"nas-v2-job-{service_id}-{index}.service"


def render_runner(service_id: str, index: int, *, spec_path: str, schema_path: str) -> str:
    return "\n".join(
        [
            MARKER,
            "[Unit]",
            f"Description=Managed Services V2 scheduled job {service_id} ({index})",
            "After=network-online.target",
            "",
            "[Service]",
            "Type=oneshot",
            f"ExecStart=/run/current-system/sw/bin/nas-v2-runtime run-job {service_id} --spec {spec_path} --schema {schema_path}",
            "NoNewPrivileges=yes",
            "PrivateTmp=yes",
            "",
        ]
    )


def render_timer(service_id: str, index: int, schedule: dict[str, Any]) -> str:
    lines = [
        MARKER,
        "[Unit]",
        f"Description=Managed Services V2 timer for {service_id} ({index})",
        "",
        "[Timer]",
        f"Unit={runner_name(service_id, index)}",
    ]
    if "calendar" in schedule:
        lines.append(f"OnCalendar={schedule['calendar']}")
    elif "intervalSeconds" in schedule:
        lines.extend(["OnBootSec=1m", f"OnUnitActiveSec={int(schedule['intervalSeconds'])}s"])
    else:
        raise V2ScheduleError(f"Service {service_id}: schedule {index} has no calendar or interval")
    delay = int(schedule.get("randomizedDelaySeconds", 0))
    if delay:
        lines.append(f"RandomizedDelaySec={delay}s")
    lines.append(f"Persistent={'true' if schedule.get('persistent', True) else 'false'}")
    lines.extend(["", "[Install]", "WantedBy=timers.target", ""])
    return "\n".join(lines)


def reconcile_schedules(
    document: dict[str, Any],
    *,
    spec_path: str,
    schema_path: str,
    dry_run: bool = False,
) -> dict[str, Any]:
    desired: dict[str, str] = {}
    enabled_timers: list[str] = []
    for service_id, service in document["services"].items():
        workload = service["workload"]
        if workload["kind"] != "job" or not service.get("enabled"):
            continue
        for index, schedule in enumerate(workload.get("schedules", []), start=1):
            runner = runner_name(service_id, index)
            timer = timer_name(service_id, index)
            desired[runner] = render_runner(service_id, index, spec_path=spec_path, schema_path=schema_path)
            desired[timer] = render_timer(service_id, index, schedule)
            enabled_timers.append(timer)

    existing = {
        path.name: path
        for path in UNIT_ROOT.glob("nas-v2-job-*.service")
        if path.is_file()
    }
    existing.update({path.name: path for path in UNIT_ROOT.glob("nas-v2-job-*.timer") if path.is_file()})
    stale = sorted(set(existing) - set(desired))
    plan = {"units": sorted(desired), "timers": sorted(enabled_timers), "remove": stale}
    if dry_run:
        return plan

    for name in stale:
        path = existing[name]
        try:
            current = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if current.startswith(MARKER):
            if name.endswith(".timer"):
                subprocess.run(["systemctl", "disable", "--now", name], check=False)
            path.unlink(missing_ok=True)
    for name, text in desired.items():
        path = UNIT_ROOT / name
        if path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER):
            raise V2ScheduleError(f"Refusing to overwrite non-V2 systemd unit {path}")
        _atomic_write(path, text)
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    for timer in enabled_timers:
        subprocess.run(["systemctl", "enable", "--now", timer], check=True)
    return plan
