#!/usr/bin/env python3
"""Generic systemd-backed executable runtime for Managed Services V2."""

from __future__ import annotations

import os
import pathlib
import re
import shlex
import subprocess
import tempfile
from typing import Any

UNIT_ROOT = pathlib.Path("/run/systemd/system")
SERVICE_ID_RE = re.compile(r"^[a-z][a-z0-9-]{0,47}$")
ENV_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
MARKER = "# Generated by NixOS NAS Managed Services V2; do not edit."


class ExecRuntimeError(RuntimeError):
    pass


def unit_name(service_id: str) -> str:
    if SERVICE_ID_RE.fullmatch(service_id) is None:
        raise ExecRuntimeError(f"Invalid V2 service id {service_id!r}")
    return f"nas-v2-exec-{service_id}.service"


def _runtime(service_id: str, service: dict[str, Any]) -> dict[str, Any]:
    runtime = service.get("runtime")
    if not isinstance(runtime, dict) or runtime.get("type") != "exec":
        raise ExecRuntimeError(f"Service {service_id}: runtime.type must be exec")
    return runtime


def _safe_absolute(value: str, *, field: str) -> str:
    path = pathlib.PurePosixPath(value)
    if not path.is_absolute() or ".." in path.parts or any(char in value for char in ("\x00", "\r", "\n")):
        raise ExecRuntimeError(f"{field} must be a safe absolute path")
    return value


def runtime_command(service_id: str, service: dict[str, Any]) -> list[str]:
    runtime = _runtime(service_id, service)
    command = runtime.get("command")
    if not isinstance(command, list) or not command or any(not isinstance(item, str) or not item for item in command):
        raise ExecRuntimeError(f"Service {service_id}: exec command must be a non-empty string array")
    executable = command[0]
    if not executable.startswith("/"):
        raise ExecRuntimeError(f"Service {service_id}: exec command[0] must be an absolute path")
    _safe_absolute(executable, field=f"Service {service_id} executable")
    return list(command)


def _atomic_write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = pathlib.Path(name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _apply_common_policy(lines: list[str], service_id: str, service: dict[str, Any]) -> None:
    resources = service.get("resources") or {}
    memory_high = resources.get("memoryHighBytes")
    memory_max = resources.get("memoryMaxBytes")
    cpus = resources.get("cpus")
    pids = resources.get("pids")
    if memory_high is not None:
        lines.append(f"MemoryHigh={int(memory_high)}")
    if memory_max is not None:
        lines.append(f"MemoryMax={int(memory_max)}")
    if cpus is not None:
        lines.append(f"CPUQuota={float(cpus) * 100:g}%")
    if pids is not None:
        lines.append(f"TasksMax={int(pids)}")

    sandbox = service.get("sandbox") or {}
    profile = sandbox.get("profile", "inherit")
    if profile != "inherit":
        if profile in {"strict", "standard"}:
            lines.extend(["NoNewPrivileges=yes", "PrivateTmp=yes"])
        if sandbox.get("readOnlyRoot") is True:
            lines.append("ProtectSystem=strict")
        writable = sandbox.get("writablePaths") or []
        if writable:
            paths = " ".join(shlex.quote(_safe_absolute(str(path), field=f"Service {service_id} writable path")) for path in writable)
            lines.append(f"ReadWritePaths={paths}")
        if sandbox.get("dropAllLinuxCapabilities") is True:
            lines.append("CapabilityBoundingSet=")
        caps = sandbox.get("addLinuxCapabilities") or []
        if caps:
            lines.append(f"AmbientCapabilities={' '.join(str(cap) for cap in caps)}")

    resolved_devices = service.get("resolvedDevices") or []
    device_paths = sorted(
        {
            str(path)
            for request in resolved_devices
            if isinstance(request, dict)
            for path in request.get("devicePaths", [])
            if isinstance(path, str) and path.startswith("/dev/")
        }
    )
    if device_paths:
        lines.append("DevicePolicy=closed")
        for path in device_paths:
            lines.append(f"DeviceAllow={path} rw")


def render_unit(service_id: str, service: dict[str, Any]) -> str:
    runtime = _runtime(service_id, service)
    command = runtime_command(service_id, service)
    workload = service.get("workload") or {}
    lines = [
        MARKER,
        "[Unit]",
        f"Description=Managed Services V2 executable runtime: {service_id}",
        "After=network-online.target",
        "",
        "[Service]",
        "Type=simple" if workload.get("kind") != "job" else "Type=oneshot",
        f"ExecStart={' '.join(shlex.quote(item) for item in command)}",
    ]
    working = runtime.get("workingDirectory")
    if working is not None:
        lines.append(f"WorkingDirectory={_safe_absolute(str(working), field=f'Service {service_id} workingDirectory')}")
    user = runtime.get("user")
    if user:
        lines.append(f"User={user}")
    group = runtime.get("group")
    if group:
        lines.append(f"Group={group}")
    environment = runtime.get("environment") or {}
    if not isinstance(environment, dict):
        raise ExecRuntimeError(f"Service {service_id}: environment must be an object")
    for key, value in sorted(environment.items()):
        if ENV_RE.fullmatch(str(key)) is None or not isinstance(value, str) or any(c in value for c in ("\x00", "\r", "\n")):
            raise ExecRuntimeError(f"Service {service_id}: invalid environment entry {key!r}")
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'Environment="{key}={escaped}"')
    for credential in service.get("credentials", []):
        if isinstance(credential, dict) and credential.get("use") == "environment-file":
            source = credential.get("resolvedPath")
            if isinstance(source, str) and source.startswith("/run/nas-secrets/"):
                lines.append(f"EnvironmentFile={source}")
    _apply_common_policy(lines, service_id, service)
    if workload.get("kind") == "daemon":
        restart = runtime.get("restart", "on-failure")
        if restart != "no":
            lines.extend([f"Restart={restart}", f"RestartSec={int(runtime.get('restartSeconds', 3))}"])
    lines.extend(["", "[Install]", "WantedBy=multi-user.target", ""])
    return "\n".join(lines)


def materialize_exec(service_id: str, service: dict[str, Any], *, dry_run: bool = False) -> dict[str, Any]:
    unit = unit_name(service_id)
    path = UNIT_ROOT / unit
    plan = {"service": service_id, "runtime": "exec", "unit": unit, "unitPath": str(path)}
    if dry_run:
        return plan
    if path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER):
        raise ExecRuntimeError(f"Refusing to overwrite non-V2 unit {path}")
    _atomic_write(path, render_unit(service_id, service))
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    return plan


def apply_exec(service_id: str, service: dict[str, Any], *, dry_run: bool = False) -> dict[str, Any]:
    plan = materialize_exec(service_id, service, dry_run=dry_run)
    workload = service.get("workload") or {}
    managed = bool(service.get("managed", True))
    enabled = bool(service.get("enabled"))
    operation = None
    if managed and not enabled:
        operation = "stop"
    elif workload.get("kind") == "daemon" and workload.get("activation") == "persistent" and enabled:
        operation = "restart"
    plan["operation"] = operation
    if operation is not None and not dry_run:
        subprocess.run(["systemctl", operation, plan["unit"]], check=True)
    return plan
