# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: NAS automation
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - model: authentik_rbac.role
    identifiers:
      name: NAS automation
    attrs:
      permissions:
        - authentik_core.view_user
        - authentik_core.add_user
        - authentik_core.change_user
        - authentik_core.reset_user_password
        - authentik_core.view_group
        - authentik_core.add_group
        - authentik_core.change_group
        - authentik_core.enable_group_superuser
        - authentik_core.view_token
        - authentik_outposts.view_outpost
